In [1]:
import pandas as pd
from pathlib import Path

### **Data Source**

In [2]:
BASE_DIR = Path.cwd().resolve().parents[0]
sales = pd.read_csv(f"{BASE_DIR}/data/gold/sales.csv")
customer = pd.read_csv(f"{BASE_DIR}/data/gold/customer.csv")
product = pd.read_csv(f"{BASE_DIR}/data/gold/product.csv")
dim_date = pd.read_csv(f"{BASE_DIR}/data/dim/dim_date.csv")

### **Sales Table**
---

In [3]:
sales.head(5)

,sales_key,order_number,product_key,customer_key,date_key,order_date,ship_date,delivery_date,price,quantity,amount
0,1,SO43697,BK-R93R-62,21768,20230814,2023-08-14,2023-08-16,2023-08-20,3578.0,1,3578.0
1,2,SO43698,BK-M82S-44,28389,20240401,2024-04-01,2024-04-04,2024-04-07,3400.0,1,3400.0
2,3,SO43699,BK-M82S-44,25863,20240520,2024-05-20,2024-05-22,2024-05-26,3400.0,1,3400.0
3,4,SO43700,BK-R50B-62,14501,20250516,2025-05-16,2025-05-20,2025-05-23,699.0,1,699.0
4,5,SO43701,BK-M82S-44,11003,20240702,2024-07-02,2024-07-03,2024-07-07,3400.0,1,3400.0

#### **Size**

In [4]:
sales.shape

(59168, 11)

In [5]:
sales.columns

Index(['sales_key', 'order_number', 'product_key', 'customer_key', 'date_key',
       'order_date', 'ship_date', 'delivery_date', 'price', 'quantity',
       'amount'],
      dtype='object')

#### **Data Types**

In [6]:
sales.dtypes

sales_key          int64
order_number      object
product_key       object
customer_key       int64
date_key           int64
order_date        object
ship_date         object
delivery_date     object
price            float64
quantity           int64
amount           float64
dtype: object

#### **Null Values**

In [7]:
sales.isnull().sum()

sales_key         0
order_number      0
product_key       0
customer_key      0
date_key          0
order_date        0
ship_date         0
delivery_date    25
price             0
quantity          0
amount            0
dtype: int64

#### **Statistics Summary**

In [8]:
sales[["price", "quantity", "amount"]].describe()

              price      quantity        amount
count  59168.000000  59168.000000  59168.000000
mean     485.508941      1.132251    547.956040
std      927.881374      0.339364   1101.470086
min        2.000000      1.000000      2.000000
25%        8.000000      1.000000      9.000000
50%       30.000000      1.000000     35.000000
75%      540.000000      1.000000    540.000000
max     3578.000000      5.000000   7156.000000

### **Product Table**
---

In [9]:
product.head(5)

,product_key,product_name,category,subcategory,product_line,maintenance,cost,launch_date,last_order_date
0,BB-7421,LL Bottom Bracket,Components,Bottom Brackets,NaN,Yes,24.0,2013-01-07,NaN
1,BB-8107,ML Bottom Bracket,Components,Bottom Brackets,NaN,Yes,45.0,2013-01-07,NaN
2,BB-9108,HL Bottom Bracket,Components,Bottom Brackets,NaN,Yes,54.0,2013-01-07,NaN
3,BC-M005,Mountain Bottle Cage,Accessories,Bottles and Cages,Mountain,No,4.0,2013-01-07,NaN
4,BC-R205,Road Bottle Cage,Accessories,Bottles and Cages,Road,No,3.0,2013-01-07,NaN

#### **Size**

In [10]:
product.shape

(295, 9)

In [11]:
product.columns

Index(['product_key', 'product_name', 'category', 'subcategory',
       'product_line', 'maintenance', 'cost', 'launch_date',
       'last_order_date'],
      dtype='object')

#### **Data Type**

In [12]:
product.dtypes

product_key         object
product_name        object
category            object
subcategory         object
product_line        object
maintenance         object
cost               float64
launch_date         object
last_order_date    float64
dtype: object

#### **Null Values**

In [13]:
product.isnull().sum()

product_key          0
product_name         0
category             7
subcategory          7
product_line        17
maintenance          7
cost                 0
launch_date          0
last_order_date    295
dtype: int64

#### **Statistics Summary**

In [14]:
product["cost"].max() - product["cost"].min()

np.float64(2171.0)

In [15]:
product[["cost"]].describe()

              cost
count   295.000000
mean    418.830508
std     520.211742
min       0.000000
25%      31.500000
50%     200.000000
75%     602.000000
max    2171.000000

### **Customer Table**
---

In [16]:
customer.head(5)

,customer_key,first_name,last_name,gender,age,age_group,marital_status,country,birthdate
0,11000,Jon,Yang,Male,42.0,adult,Married,Australia,1971-10-06
1,11001,Eugene,Huang,Male,37.0,adult,Single,Australia,1976-05-10
2,11002,Ruben,Torres,Male,42.0,adult,Married,Australia,1971-02-09
3,11003,Christy,Zhu,Female,40.0,adult,Single,Australia,1973-08-14
4,11004,Elizabeth,Johnson,Female,34.0,young adult,Single,Australia,1979-08-05

#### **Size**

In [17]:
customer.shape

(18484, 9)

In [18]:
customer.columns

Index(['customer_key', 'first_name', 'last_name', 'gender', 'age', 'age_group',
       'marital_status', 'country', 'birthdate'],
      dtype='object')

#### **Data Type**

In [19]:
customer.dtypes

customer_key        int64
first_name         object
last_name          object
gender             object
age               float64
age_group          object
marital_status     object
country            object
birthdate          object
dtype: object

#### **Null Values**

In [20]:
customer.isnull().sum()

customer_key        0
first_name          3
last_name           2
gender             15
age                16
age_group         291
marital_status      2
country           337
birthdate          16
dtype: int64